/**
 * MagicMirror Module: Daily Zapiro
 * A MagicMirror² Module to show cartoons by Zapiro.
 * 
 * Version 1.0.0
 * By Courtney Pitcher
 * 
 * License CC-BY-SA-NC-4.0
 * 
 * This is an autogenerated file. DO NOT EDIT!
 */

'use strict';

var NodeHelper = require('node_helper');
var Log = require('logger');
var fetch = require('node-fetch');
var fastXmlParser = require('fast-xml-parser');

function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
// noinspection JSVoidFunctionReturnValueUsed
module.exports = NodeHelper.create({
    start: function () {
        Log.log("Starting node helper for: " + this.name);
    },
    socketNotificationReceived: function (notification, payload) {
        var _this = this;
        if (notification === "REQUEST_ZAPIRO_CARTOON") {
            var url = 'https://www.dailymaverick.co.za/cartoon-sitemap2.xml';
            fetch(url)
                .then(function (response) { return response.text(); })
                .then(function (text) {
                Log.info("".concat(_this.name, ": Retrieving a new comic"));
                var parser = new fastXmlParser.XMLParser();
                var jObj = parser.parse(text);
                var comicUrls = jObj.urlset.url;
                var latestComic = comicUrls[comicUrls.length - 1 - getRandomInt(0, payload.mostRecentNComics - 1)];
                var comicUrl = latestComic['image:image']['image:loc'];
                _this.sendSocketNotification("ZAPIRO_CARTOON", { url: comicUrl });
            });
        }
    },
});
